print('To Everyone,')
print('')
print("Keep going — you're doing better than you think.")
print('Every small step you take now is building the future you’ve always dreamed of. Even when it feels slow, you’re growing. Don’t forget why you started.')
print('')
print('Trust the process, Believe in your fire!')
print('You’ve got this 💪')
print('')
print('– Sakshi ❤️')