# Snail Mail 💌
# Codédex

print('+-------------------------------------------------------------------------------------------+')
print('|                                                                                           |')
print('|                                                                        Oct 29th, 2025     |')
print('|                                                                          Brooklyn, NY     |')
print('|                                                                                           |')
print('|         Dear Self,                                                                        |')
print('|                                                                                           |')
print('|         Does great art require suffering?                                                 |')
print('|         Does great product require capital?                                               |')
print('|         Did you find some truth at the end of this road?                                  |')
print('|                                                                                           |')
print('|         Regardless, go build the learning platform you always dreamed of —                |')
print('|         the one you wish existed when you first started.                                  |')
print('|                                                                                           |')
print('|         Give more than you take.                                                          |')
print('|         Take less than you need.                                                          |')
print('|                                                                                           |')
print('|         And when things fall apart, get tf back up.                                       |')
print('|                                                                                           |')
print('|         - Sonny 🤠                                                                        |')
print('|                                                                                           |')
print('|         P.S. Hope I made you proud. You got this, kiddo. Go get ’em.                      |')
print('|                                                                                           |')
print('+-------------------------------------------------------------------------------------------+')
