# Snail Mail 💌
# Codédex

print('+---------------------------------------------------------------------------------+')
print('|                                                                                 |')
print('|                                                                 October 2025    |')
print('|                                                                 Brooklyn, NY    |')
print('|       Dear Self,                                                                |')
print('|                                                                                 |')
print('|       Does great art require suffering?                                         |')
print('|       Does great product demand capital?                                        |')
print('|       Did you find any truth at the end of the road?                            |')
print('|                                                                                 |')
print('|       Regardless, go build the learning platform you’ve always dreamed of —     |')
print('|       the one you wish existed when you first started.                          |')
print('|                                                                                 |')
print('|       Give more than you take.                                                  |')
print('|       Take just what you need.                                                  |')
print('|                                                                                 |')
print('|       And when things fall apart, get tf back up.                               |')
print('|                                                                                 |')
print('|       - Sonny Li                                                                |')
print('|                                                                                 |')
print('|       P.S. Hope I made you proud. You got this, kiddo. 🤠                       |')
print('|                                                                                 |')
print('+---------------------------------------------------------------------------------+')
